# Generated by Django 4.1.2 on 2023-01-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0008_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_id',
            field=models.TextField(default='0', max_length=20),
        ),
    ]
