# Generated by Django 4.1.2 on 2023-01-30 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0009_category_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_id',
        ),
    ]
