# Generated by Django 4.1.2 on 2023-01-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RozetkaItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('href', models.CharField(max_length=200)),
                ('current_price', models.CharField(max_length=10)),
                ('old_price', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
            ],
        ),
    ]
