# Generated by Django 4.1.2 on 2023-01-23 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_ids', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(default='No id', max_length=20)),
                ('title', models.CharField(default='No title', max_length=200)),
                ('href', models.CharField(default='No link', max_length=200)),
                ('current_price', models.CharField(default='0', max_length=10)),
                ('old_price', models.CharField(default='0', max_length=10)),
                ('brand', models.CharField(default='No brand', max_length=20)),
                ('category', models.CharField(default='No category', max_length=20)),
            ],
        ),
    ]
