# Generated by Django 4.1.2 on 2023-01-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sell_status',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
