# Generated by Django 4.1.2 on 2023-01-30 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0005_rename_category_category_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='category_title',
        ),
    ]
