# Generated by Django 4.1.2 on 2023-01-30 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0006_rename_category_name_category_category_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
