# Generated by Django 4.1.2 on 2023-01-30 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0002_category_alter_product_brand_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
